/* eslint-disable import/no-unused-modules */
/* eslint-disable no-unused-labels */
export const FILES_BY_ADDRESS = {
  STRATIS: {
    FACTORY_V3: [
      '/patches/smart-order-router/build/module/util/addresses.js',
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/patches/v3-sdk/dist/constants.d.ts',
      '/patches/v3-sdk/dist/v3-sdk.cjs.production.min.js.map',
      '/patches/v3-sdk/dist/v3-sdk.esm.js',
      '/patches/v3-sdk/dist/v3-sdk.cjs.development.js.map',
      '/patches/v3-sdk/dist/v3-sdk.cjs.production.min.js',
      '/patches/v3-sdk/dist/v3-sdk.cjs.development.js',
      '/node_modules/@uniswap/smart-order-router/build/module/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/v3-sdk/dist/constants.d.ts',
      '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.production.min.js.map',
      '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.esm.js',
      '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.development.js.map',
      '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.production.min.js',
      '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.development.js',
      '/src/constants/addresses.ts',
    ],
    WSTRAX: [
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.esm.js',
      '/patches/smart-order-router/build/module/util/chains.js',
      '/patches/smart-order-router/build/module/util/addresses.js',
      '/patches/smart-order-router/build/module/providers/token-provider.js',
      '/patches/smart-order-router/build/main/util/chains.js',
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/patches/smart-order-router/build/main/providers/token-provider.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.esm.js',
      '/node_modules/@uniswap/smart-order-router/build/module/util/chains.js',
      '/node_modules/@uniswap/smart-order-router/build/module/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/module/providers/token-provider.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/chains.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/providers/token-provider.js',
      '/src/constants/tokens.ts',
      '/src/state/routing/slice.ts',
    ],
    MULTICALL: [
      '/patches/smart-order-router/build/module/util/addresses.js',
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/module/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/src/constants/addresses.ts',
    ],
    QUOTER: [
      '/patches/smart-order-router/build/module/util/addresses.js',
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/module/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/src/constants/addresses.ts',
    ],
    NFT_DESCRIPTOR: [''],
    NONFUNGIBLE_TOKEN_POSITION_DESCRIPTOR: [''],
    NONFUNGIBLE_POSITION_MANAGER: [
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/src/constants/addresses.ts',
    ],
    SWAP_ROUTER: [''],
    V3_MIGRATOR: [
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/src/constants/addresses.ts',
    ],
    TICK_LENS: [
      '/patches/smart-order-router/build/main/util/addresses.js',
      '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
      '/src/constants/addresses.ts',
    ],
    PERMIT2: [
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.esm.js.map',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js.map',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
      '/patches/universal-router-sdk/dist/utils/constants.d.ts',
      '/patches/universal-router-sdk/dist/universal-router-sdk.esm.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js.map',
      '/patches/permit2-sdk/dist/constants.d.ts',
      '/patches/permit2-sdk/dist/permit2-sdk.cjs.production.min.js',
      '/patches/permit2-sdk/dist/permit2-sdk.cjs.development.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.esm.js.map',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js.map',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/utils/constants.d.ts',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.esm.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js.map',
      '/node_modules/@uniswap/permit2-sdk/dist/constants.d.ts',
      '/node_modules/@uniswap/permit2-sdk/dist/permit2-sdk.cjs.production.min.js',
      '/node_modules/@uniswap/permit2-sdk/dist/permit2-sdk.cjs.development.js',
    ],
    UNSUPPORTED_PROTOCOL: [''],
    UNIVERSAL_ROUTER: [
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js.map',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.esm.js',
      '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js.map',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js.map',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.esm.js',
      '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js.map',
    ],
    TOKENS: {
      USDT: [
        '/patches/smart-order-router/build/module/providers/token-provider.js',
        '/patches/smart-order-router/build/main/providers/token-provider.js',
        '/node_modules/@uniswap/smart-order-router/build/module/providers/token-provider.js',
        '/node_modules/@uniswap/smart-order-router/build/main/providers/token-provider.js',
        '/src/constants/tokens.ts',
        '/src/state/routing/slice.ts',
      ],
      USDC: [
        '/patches/smart-order-router/build/module/providers/token-provider.js',
        '/patches/smart-order-router/build/main/providers/token-provider.js',
        '/node_modules/@uniswap/smart-order-router/build/module/providers/token-provider.js',
        '/node_modules/@uniswap/smart-order-router/build/main/providers/token-provider.js',
        '/src/constants/tokens.ts',
      ],
    },
  },
  WMATIC: [
    '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
    '/patches/universal-router-sdk/dist/universal-router-sdk.esm.js.map',
    '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.development.js.map',
    '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
    '/patches/universal-router-sdk/dist/universal-router-sdk.esm.js',
    '/patches/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js.map',
    '/patches/smart-order-router/build/module/util/chains.js',
    '/patches/smart-order-router/build/module/providers/token-provider.js',
    '/patches/smart-order-router/build/main/util/chains.js',
    '/patches/smart-order-router/build/main/providers/token-provider.js',
    '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js',
    '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.esm.js.map',
    '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.development.js.map',
    '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js',
    '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.esm.js',
    '/node_modules/@uniswap/universal-router-sdk/dist/universal-router-sdk.cjs.production.min.js.map',
    '/node_modules/@uniswap/smart-order-router/build/module/util/chains.js',
    '/node_modules/@uniswap/smart-order-router/build/module/providers/token-provider.js',
    '/node_modules/@uniswap/smart-order-router/build/main/util/chains.js',
    '/node_modules/@uniswap/smart-order-router/build/main/providers/token-provider.js',
    '/node_modules/@uniswap/widgets/dist/index-20d21b03.js',
    '/node_modules/@uniswap/widgets/dist/cjs/index-28381861.cjs',
  ],
  FACTORY_V3: ['/patches/v3-sdk/dist/v3-sdk.esm.js.map', '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.esm.js.map'],
  FACTORY_V2: [
    '/node_modules/@uniswap/v2-sdk/dist/constants.d.ts',
    '/node_modules/@uniswap/v2-sdk/dist/v2-sdk.cjs.development.js.map',
    '/node_modules/@uniswap/v2-sdk/dist/v2-sdk.cjs.production.min.js',
    '/node_modules/@uniswap/v2-sdk/dist/v2-sdk.cjs.production.min.js.map',
    '/node_modules/@uniswap/v2-sdk/dist/v2-sdk.esm.js.map',
    '/node_modules/@uniswap/v2-sdk/dist/v2-sdk.esm.js',
    '/node_modules/@uniswap/v2-sdk/dist/v2-sdk.cjs.development.js',
    '/src/state/swap/hooks.tsx',
  ],
  V3_POOL_INIT_CODE_HASH: [
    '/patches/v3-sdk/dist/constants.d.ts',
    '/patches/v3-sdk/dist/v3-sdk.cjs.production.min.js.map',
    '/patches/v3-sdk/dist/v3-sdk.esm.js',
    '/patches/v3-sdk/dist/v3-sdk.cjs.development.js.map',
    '/patches/v3-sdk/dist/v3-sdk.esm.js.map',
    '/patches/v3-sdk/dist/v3-sdk.cjs.production.min.js',
    '/patches/v3-sdk/dist/v3-sdk.cjs.development.js',
    '/node_modules/@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol',
    '/node_modules/@uniswap/router-sdk/node_modules/@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol',
    '/node_modules/@uniswap/v3-sdk/dist/constants.d.ts',
    '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.production.min.js.map',
    '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.esm.js',
    '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.development.js.map',
    '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.esm.js.map',
    '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.production.min.js',
    '/node_modules/@uniswap/v3-sdk/dist/v3-sdk.cjs.development.js',
  ],
  MULTICALL: [
    '/patches/smart-order-router/build/module/util/addresses.js',
    '/patches/smart-order-router/build/main/util/addresses.js',
    '/node_modules/@uniswap/redux-multicall/dist/integration-tests/consts.d.ts',
    '/node_modules/@uniswap/smart-order-router/build/module/util/addresses.js',
    '/node_modules/@uniswap/smart-order-router/build/main/util/addresses.js',
    '/node_modules/@uniswap/widgets/dist/index-20d21b03.js',
    '/node_modules/@uniswap/widgets/dist/cjs/index-28381861.cjs',
    '/src/constants/addresses.ts',
  ],
  QUOTER: [''],
  NONFUNGIBLE_POSITION_MANAGER: [
    '/patches/smart-order-router/build/module/util/addresses.d.ts',
    '/patches/smart-order-router/build/module/util/addresses.js',
    '/patches/smart-order-router/build/main/util/addresses.d.ts',
    '/src/constants/addresses.ts',
  ],
  V3_MIGRATOR: [
    '/patches/smart-order-router/build/module/util/addresses.d.ts',
    '/patches/smart-order-router/build/module/util/addresses.js',
    '/patches/smart-order-router/build/main/util/addresses.d.ts',
    '/src/constants/addresses.ts',
  ],
  PERMIT2: ['/src/components/AccountDrawer/MiniPortfolio/Activity/parseRemote.tsx'],
  TOKENS: {
    USDC: [
      '/patches/smart-order-router/build/module/providers/token-provider.js',
      '/patches/smart-order-router/build/main/providers/token-provider.js',
      '/node_modules/@uniswap/widgets/dist/index-20d21b03.js',
      '/node_modules/@uniswap/widgets/dist/cjs/index-28381861.cjs',
    ],
    DAI: [
      '/patches/smart-order-router/build/module/providers/token-provider.js',
      '/patches/smart-order-router/build/main/providers/token-provider.js',
      '/node_modules/@uniswap/widgets/dist/index-20d21b03.js',
      '/node_modules/@uniswap/widgets/dist/cjs/index-28381861.cjs',
    ],
  },
}
